### PR TITLE
Set correct reference to shell_profiles.

### PR DESCRIPTION
**Pull request by joestewart**
fubarhouse_python -> fubarhouse_nvm

### CODE REVIEW

**Comment by fubarhouse** [comment]
I noted this in an overhaul I've been working on in the past few days, but thank you!

**Comment by fubarhouse** [comment]
@joestewart I've added the overhauled role early for you - there was some testing to be completed on RedHat, but it adds support for Darwin and RedHat among many other systematic improvements.

It's essentially ready for use and the vms I look after are beginning to use the new roles.

**Comment by joestewart** [comment]
Thanks!  The simplified defaults are very helpful.  That and the Redhat support were the next two things that I had noted. :)  

Maybe time for a release tag?

thanks again, seems to be working great.

**Comment by fubarhouse** [comment]
@joestewart I'll organise a release tag once testing is complete across all the updated roles. There are some dependency issues on redhat I wish to either document or resolve on the python and pm2 roles, but the changes are universal among all of them other than the behat role which I might look at overhauling.

Apart from that, after documentation is updated and the meta files are correctly structured I'll certainly mark these roles as v1.0. :)

**Pull request merged**
