### PR TITLE
Link to installed path

### LINKED ISSUE #50: "NodeJS | Linking binaries" is using incorrect path
https://github.com/creationix/nvm/releases/tag/v0.23.0

"node versions v0.12.0 and later will now reside in $NVM_DIR/versions/node"

It appears that https://github.com/fubarhouse/ansible-role-nodejs/blob/master/tasks/nodejs.yml#L29

should be:

src: "{{ nvm_install_dir }}/versions/node/v{{ node_version }}/bin/{{ item }}"

### PR DESCRIPTION
**Pull request by joestewart**
This fixes #50 for me.

Curious about tests.

### CODE REVIEW

**Comment by fubarhouse** [comment]
I apologise for the delay, I wasn't even aware of your PR's.

I'm happy with this - though typically it will only install as root when the user running the ansible playbook is root. So typically if you run the role as a user (example below), this isn't actually a problem.

Until somebody speaks out, I expect this to work as intended based off the existing `fubarhouse_user` variable.

Example (source https://github.com/fubarhouse/drupal-vm/blob/master/provisioning/tasks/post.yml)
```
- name: Include fubarhouse.golang role
  become: yes
  become_user: vagrant
  include_role:
    name: fubarhouse.golang
  when: '"golang" in installed_extras'
```

**Comment by joestewart** [comment]
Thanks!  Any chance to tag a patch release?

**Comment by fubarhouse** [comment]
I'll get it done today!

edit: I'm just waiting for the tests on c53af01e02b0892c36491de153f78ac76688b8af to pass.

**Comment by fubarhouse** [comment]
Version 1.8.4 is now available via Ansible Galaxy.

**Pull request merged**
